<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    protected $table="customers";
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table($this->table, function (Blueprint $table) {
            $table->unique("email","customers_unique_email");
            $table->unsignedTinyInteger("auth_created")->default(0)->index();
            $table->unsignedBigInteger("auth_id")->nullable()->index()->comment("identifier of login generated by auth_service");
            $table->string("auth_comment")->nullable();
            $table->timestamp("auth_at")->nullable();

        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table($this->table, function (Blueprint $table) {
            $table->dropColumn("auth_created");
            $table->dropColumn("auth_id");
            $table->dropColumn("auth_at");
            $table->dropColumn("auth_comment");
            $table->dropIndex("customers_unique_email");
        });
    }
};
